from enum import Enum


class QuestionTarget(str, Enum):
    CUSTOMER = "CUSTOMER"
    MANUFACTURER = "MANUFACTURER"
    INTERNAL = "INTERNAL"


class QuestionStatus(str, Enum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    PARTIAL = "PARTIAL"
    ANSWERED = "ANSWERED"
    FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"
    CLOSED = "CLOSED"


class FactConfidence(str, Enum):
    MANUFACTURER_CONFIRMED = "MANUFACTURER_CONFIRMED"
    SPACEONE_VERIFIED = "SPACEONE_VERIFIED"
    CUSTOMER_INFORMATION = "CUSTOMER_INFORMATION"
    PAST_CASE = "PAST_CASE"
    AI_EXTRACTED_UNVERIFIED = "AI_EXTRACTED_UNVERIFIED"


class RecommendationOrigin(str, Enum):
    CUSTOMER_REQUESTED = "CUSTOMER_REQUESTED"
    MANUFACTURER_RECOMMENDED = "MANUFACTURER_RECOMMENDED"
    SPACEONE_PROPOSAL = "SPACEONE_PROPOSAL"
    AI_SUGGESTED = "AI_SUGGESTED"


class RelationType(str, Enum):
    REQUIRES = "REQUIRES"
    RECOMMENDS = "RECOMMENDS"
    OPTIONAL = "OPTIONAL"
    COMPATIBLE_WITH = "COMPATIBLE_WITH"
    NOT_COMPATIBLE_WITH = "NOT_COMPATIBLE_WITH"
    INTEGRATION_REQUIRED = "INTEGRATION_REQUIRED"
    SHARED_DEVICE = "SHARED_DEVICE"
    REPLACED_BY = "REPLACED_BY"


class ValidationSeverity(str, Enum):
    BLOCKER = "BLOCKER"
    WARNING = "WARNING"
    INFO = "INFO"
