from enum import Enum


class QuestionTarget(str, Enum):
    CUSTOMER = "CUSTOMER"
    MANUFACTURER = "MANUFACTURER"
    INTERNAL = "INTERNAL"


class QuestionStatus(str, Enum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    PARTIAL = "PARTIAL"
    ANSWERED = "ANSWERED"
    FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"
    CLOSED = "CLOSED"


class SuggestedQuestionStatus(str, Enum):
    ANSWERED = "ANSWERED"
    PARTIAL = "PARTIAL"
    FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"


class MatchConfidence(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class AnswerSourceType(str, Enum):
    MANUFACTURER_RESPONSE = "MANUFACTURER_RESPONSE"


class FactScope(str, Enum):
    CASE_ONLY = "CASE_ONLY"
    PRODUCT_REUSABLE = "PRODUCT_REUSABLE"


class FactConfidence(str, Enum):
    MANUFACTURER_CONFIRMED = "MANUFACTURER_CONFIRMED"
    SPACEONE_VERIFIED = "SPACEONE_VERIFIED"
    CUSTOMER_INFORMATION = "CUSTOMER_INFORMATION"
    PAST_CASE = "PAST_CASE"
    AI_EXTRACTED_UNVERIFIED = "AI_EXTRACTED_UNVERIFIED"


class RecommendationOrigin(str, Enum):
    CUSTOMER_REQUESTED = "CUSTOMER_REQUESTED"
    MANUFACTURER_RECOMMENDED = "MANUFACTURER_RECOMMENDED"
    SPACEONE_PROPOSAL = "SPACEONE_PROPOSAL"
    AI_SUGGESTED = "AI_SUGGESTED"


class RelationType(str, Enum):
    REQUIRES = "REQUIRES"
    RECOMMENDS = "RECOMMENDS"
    OPTIONAL = "OPTIONAL"
    COMPATIBLE_WITH = "COMPATIBLE_WITH"
    NOT_COMPATIBLE_WITH = "NOT_COMPATIBLE_WITH"
    INTEGRATION_REQUIRED = "INTEGRATION_REQUIRED"
    SHARED_DEVICE = "SHARED_DEVICE"
    REPLACED_BY = "REPLACED_BY"


class ValidationSeverity(str, Enum):
    BLOCKER = "BLOCKER"
    WARNING = "WARNING"
    INFO = "INFO"


class PriceBookDiffType(str, Enum):
    NEW_SKU = "NEW_SKU"
    PRICE_CHANGED = "PRICE_CHANGED"
    DESCRIPTION_CHANGED = "DESCRIPTION_CHANGED"
    NOTES_CHANGED = "NOTES_CHANGED"
    REMOVED_SKU = "REMOVED_SKU"
    UNCHANGED = "UNCHANGED"


class SkuSourceStatus(str, Enum):
    ACTIVE = "ACTIVE"
    OBSOLETE = "OBSOLETE"


class SkuDuplicateClass(str, Enum):
    DUPLICATE_SAME = "DUPLICATE_SAME"
    DUPLICATE_CONTEXT_DIFFERENT = "DUPLICATE_CONTEXT_DIFFERENT"
    PRICE_CONFLICT = "PRICE_CONFLICT"


class RecordStatus(str, Enum):
    CANDIDATE = "CANDIDATE"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class YesNoUnknown(str, Enum):
    YES = "YES"
    NO = "NO"
    UNKNOWN = "UNKNOWN"


class ShippingType(str, Enum):
    LARGE_BOX = "LARGE_BOX"
    SMALL_BOX = "SMALL_BOX"
    PIPE_TREKKER = "PIPE_TREKKER"
    CUSTOM = "CUSTOM"


class DestinationRegion(str, Enum):
    USA = "USA"
    EUROPE_UK = "EUROPE_UK"
    GLOBAL = "GLOBAL"
    JAPAN = "JAPAN"
    CUSTOM = "CUSTOM"


class ShippingScopeType(str, Enum):
    STANDARD = "STANDARD"
    CASE_SPECIFIC = "CASE_SPECIFIC"


class UpdateSourceType(str, Enum):
    DEALER_UPDATE_EMAIL = "DEALER_UPDATE_EMAIL"
    DIRECT_EMAIL = "DIRECT_EMAIL"
    WHATSAPP = "WHATSAPP"
    SUPPLIER_QUOTE = "SUPPLIER_QUOTE"
    MEETING = "MEETING"
    PHONE = "PHONE"
    MANUAL = "MANUAL"


class UpdateCategory(str, Enum):
    SHIPPING = "SHIPPING"
    LEAD_TIME = "LEAD_TIME"
    PRODUCT_SPEC = "PRODUCT_SPEC"
    PRICE = "PRICE"
    PRODUCT_STATUS = "PRODUCT_STATUS"
    WARRANTY = "WARRANTY"
    FIRMWARE = "FIRMWARE"
    MARKETING_MATERIAL = "MARKETING_MATERIAL"
    OTHER = "OTHER"


class UpdateConfidence(str, Enum):
    RULE_BASED_UNVERIFIED = "RULE_BASED_UNVERIFIED"
    MANUAL_UNVERIFIED = "MANUAL_UNVERIFIED"


class LinkStatus(str, Enum):
    AUTO_LINKED = "AUTO_LINKED"
    MANUALLY_LINKED = "MANUALLY_LINKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    UNLINKED = "UNLINKED"
    NO_LINK_REQUIRED = "NO_LINK_REQUIRED"


class LinkMethod(str, Enum):
    AUTO_SKU_MATCH = "AUTO_SKU_MATCH"
    MANUAL_SKU_ENTRY = "MANUAL_SKU_ENTRY"
    NONE = "NONE"


class MatchStatus(str, Enum):
    EXACT_MATCH = "EXACT_MATCH"
    PRICE_MISMATCH = "PRICE_MISMATCH"
    PRICE_MISSING = "PRICE_MISSING"
    SKU_NOT_FOUND = "SKU_NOT_FOUND"
    PART_NUMBER_INVALID = "PART_NUMBER_INVALID"
    OBSOLETE_ONLY = "OBSOLETE_ONLY"
    SOURCE_PRICE_CONFLICT = "SOURCE_PRICE_CONFLICT"
    MULTIPLE_SPACEONE_ROWS = "MULTIPLE_SPACEONE_ROWS"
    NO_MANUFACTURER_PRICE = "NO_MANUFACTURER_PRICE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
